# Regenerates data.js from maintenance_requests.csv.
# Run this after editing the CSV if you open index.html directly (double-click,
# file:// URL) instead of serving it through a local web server.
# Usage:  powershell -ExecutionPolicy Bypass -File generate-data.ps1

$ErrorActionPreference = "Stop"
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$csvPath = Join-Path $here "maintenance_requests.csv"
$outPath = Join-Path $here "data.js"

$csvText = Get-Content -Raw -Path $csvPath -Encoding UTF8
$csvText = $csvText -replace "`r`n", "`n"
$csvText = $csvText.TrimEnd("`n")

$bt = [char]96

$lines = @()
$lines += "// Auto-generated by generate-data.ps1 from maintenance_requests.csv."
$lines += "// Do not edit by hand -- edit the CSV, then re-run generate-data.ps1."
$lines += "const MAINTENANCE_CSV = $bt$csvText$bt;"

$content = ($lines -join "`n") + "`n"
Set-Content -Path $outPath -Value $content -Encoding UTF8 -NoNewline

Write-Host "Wrote $outPath from $csvPath"
